.TH "PiP Initialization/Finalization" 3 "Sun Jan 17 2021" "Process-in-Process" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PiP Initialization/Finalization \- 
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBpip_init\fP (int *pipidp, int *ntasks, void **root_expp, int opts)"
.br
.ti -1c
.RI "int \fBpip_fin\fP (void)"
.br
.in -1c
.SH "Detailed Description"
.PP 
PiP Initialization/Finalization

.PP
\fBDescription\fP
.RS 4
PiP initialization/finalization functions 
.RE
.PP

.SH "Function Documentation"
.PP 
.SS "int pip_init (int *pipidp, int *ntasks, void **root_expp, intopts)"

.PP
\fBName\fP
.RS 4
pip_init
.RE
.PP
\fBName\fP
.RS 4
Initialize the PiP library
.RE
.PP
\fBSynopsis\fP
.RS 4
#include <\fBpip/pip\&.h\fP> 
.br
int pip_init( int *pipidp, int *ntasks, void **root_expp, uint32_t opts );
.RE
.PP
\fBDescription\fP
.RS 4
This function initializes the PiP library\&. The PiP root process must call this\&. A PiP task is not required to call this function unless the PiP task calls any PiP functions\&. 
.RE
.PP
\fBDescription\fP
.RS 4
When this function is called by a PiP root, \fCntasks\fP, and \fCroot_expp\fP are input parameters\&. If this is called by a PiP task, then those parameters are output returning the same values input by the root\&. 
.RE
.PP
\fBDescription\fP
.RS 4
A PiP task may or may not call this function\&. If \fCpip_init\fP is not called by a PiP task explicitly, then \fCpip_init\fP is called magically and implicitly even if the PiP task program is NOT linked with the PiP library\&.
.RE
.PP
\fBParameters:\fP
.RS 4
\fIpipidp\fP When this is called by the PiP root process, then this returns \fCPIP_PIPID_ROOT\fP, otherwise it returns the PiP ID of the calling PiP task\&. 
.br
\fIntasks\fP When called by the PiP root, it specifies the maximum number of PiP tasks\&. When called by a PiP task, then it returns the number specified by the PiP root\&. 
.br
\fIroot_expp\fP If the root PiP is ready to export a memory region to any PiP task(s), then this parameter is to pass the exporting address\&. If the PiP root is not ready to export or has nothing to export then this variable can be NULL\&. When called by a PiP task, it returns the exported address by the PiP root, if any\&. 
.br
\fIopts\fP Specifying the PiP execution mode and See below\&.
.RE
.PP
\fBExecution mode option\fP
.RS 4
Users may explicitly specify the PiP execution mode\&. This execution mode can be categorized in two; process mode and thread mode\&. In the process execution mode, each PiP task may have its own file descriptors, signal handlers, and so on, just like a process\&. Contrastingly, in the pthread executionn mode, file descriptors and signal handlers are shared among PiP root and PiP tasks while maintaining the privatized variables\&. 
.RE
.PP
\fB\fP
.RS 4
To spawn a PiP task in the process mode, the PiP library modifies the \fBclone()\fP flag so that the created PiP task can exhibit the alomost same way with that of normal Linux process\&. There are three ways implmented; using LD_PRELOAD, modifying GLIBC, and modifying GIOT entry of the \fBclone()\fP systemcall\&. One of the option flag values; \fBPIP_MODE_PTHREAD\fP, \fBPIP_MODE_PROCESS\fP, \fBPIP_MODE_PROCESS_PRELOAD\fP, \fBPIP_MODE_PROCESS_PIPCLONE\fP, or \fBPIP_MODE_PROCESS_GOT\fP can be specified as the option flag\&. Or, users may specify the execution mode by the \fBPIP_MODE\fP environment described below\&.
.RE
.PP
\fBReturns:\fP
.RS 4
Zero is returned if this function succeeds\&. Otherwise an error number is returned\&.
.RE
.PP
\fBReturn values:\fP
.RS 4
\fIEINVAL\fP \fIntasks\fP is negative 
.br
\fIEBUSY\fP PiP root called this function twice or more without calling \fBpip_fin\fP\&. 
.br
\fIEPERM\fP \fIopts\fP is invalid or unacceptable 
.br
\fIEOVERFLOW\fP \fIntasks\fP is too large 
.br
\fIELIBSCN\fP verssion miss-match between PiP root and PiP task
.RE
.PP
\fBEnvironment\fP
.RS 4

.PD 0

.IP "\(bu" 2
\fBPIP_MODE\fP Specifying the PiP execution mmode\&. Its value can be either \fCthread\fP, \fCpthread\fP, \fCprocess\fP, \fCprocess:preload\fP, \fCprocess:pipclone\fP, or \fCprocess:got\fP\&. 
.IP "\(bu" 2
\fBLD_PRELOAD\fP This is required to set appropriately to hold the path to the \fCpip_preload\&.so\fP file, if the PiP execution mode is \fCPIP_MODE_PROCESS_PRELOAD\fP (the \fCopts\fP in \fCpip_init\fP) and/or the PIP_MODE ennvironment is set to \fCprocess:preload\fP\&. See also the \fCpip-mode\fP command to set the environment variable appropriately and easily\&. 
.IP "\(bu" 2
\fBPIP_STACKSZ\fP Sepcifying the stack size (in bytes)\&. The \fBKMP_STACKSIZE\fP and \fBOMP_STACKSIZE\fP are also effective\&. The 't', 'g', 'm', 'k' and 'b' posfix character can be used\&. 
.IP "\(bu" 2
\fBPIP_STOP_ON_START\fP Specifying the PIP ID to stop on start to debug the specified PiP task from the beginning\&. If the before hook is specified, then the PiP task will be stopped just before calling the before hook\&. 
.IP "\(bu" 2
\fBPIP_GDB_PATH\fP If thisenvironment is set to the path pointing to the PiP-gdb executable file, then PiP-gdb is automatically attached when an excetion signal (SIGSEGV and SIGHUP by default) is delivered\&. The signals which triggers the PiP-gdb invokation can be specified the \fCPIP_GDB_SIGNALS\fP environment described below\&. 
.IP "\(bu" 2
\fBPIP_GDB_COMMAND\fP If this PIP_GDB_COMMAND is set to a filename containing some GDB commands, then those GDB commands will be executed by the GDB in batch mode, instead of backtrace\&. 
.IP "\(bu" 2
\fBPIP_GDB_SIGNALS\fP Specifying the signal(s) resulting automatic PiP-gdb attach\&. Signal names (case insensitive) can be concatenated by the '+' or '-' symbol\&. 'all' is reserved to specify most of the signals\&. For example, 'ALL-TERM' means all signals excepting \fCSIGTERM\fP, another example, 'PIPE+INT' means \fCSIGPIPE\fP and \fCSIGINT\fP\&. Some signals such as SIGKILL and SIGCONT cannot be specified\&. 
.IP "\(bu" 2
\fBPIP_SHOW_MAPS\fP If the value is 'on' and one of the above exection signals is delivered, then the memory map will be shown\&. 
.IP "\(bu" 2
\fBPIP_SHOW_PIPS\fP If the value is 'on' and one of the above exection signals is delivered, then the process status by using the \fCpips\fP command will be shown\&.
.PP
.RE
.PP
\fBBugs\fP
.RS 4
Is is NOT guaranteed that users can spawn tasks up to the number specified by the \fIntasks\fP argument\&. There are some limitations come from outside of the PiP library (from GLIBC)\&.
.RE
.PP
\fBSee Also:\fP
.RS 4
\fBpip_named_export\fP 
.PP
\fBpip_export\fP 
.PP
\fBpip_fin\fP 
.PP
pip-mode 
.PP
pips 
.RE
.PP

.SS "int pip_fin (void)"

.PP
\fBName\fP
.RS 4
pip_fin
.RE
.PP
\fBName\fP
.RS 4
Finalize the PiP library
.RE
.PP
\fBSynopsis\fP
.RS 4
#include <\fBpip/pip\&.h\fP> 
.br
int \fBpip_fin( void )\fP;
.RE
.PP
\fBDescription\fP
.RS 4
This function finalizes the PiP library\&. After calling this, most of the PiP functions will return the error code \fCEPERM\fP\&.
.RE
.PP
\fBReturns:\fP
.RS 4
zero is returned if this function succeeds\&. On error, error number is returned\&. 
.RE
.PP
\fBReturn values:\fP
.RS 4
\fIEPERM\fP \fCpip_init\fP is not yet called 
.br
\fIEBUSY\fP \fCone\fP or more PiP tasks are not yet terminated
.RE
.PP
\fBNotes\fP
.RS 4
The behavior of calling \fBpip_init\fP after calling this \fBpip_fin\fP is not defined and recommended not to do so\&.
.RE
.PP
\fBSee Also:\fP
.RS 4
\fBpip_init\fP 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Process-in-Process from the source code\&.
