.TH "Terminating PiP Task" 3 "Tue Feb 16 2021" "Process-in-Process" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Terminating PiP Task \- 
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBpip_exit\fP (int status)"
.br
.RI "\fIterminate the calling PiP task \fP"
.ti -1c
.RI "int \fBpip_kill_all_tasks\fP (void)"
.br
.RI "\fIkill all PiP tasks \fP"
.ti -1c
.RI "void \fBpip_abort\fP (void)"
.br
.RI "\fIKill all PiP tasks and then kill PiP root\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Terminating PiP task

.PP
\fBDescription\fP
.RS 4
Function to ternminate PiP task normally or abnormally (abort)\&. 
.RE
.PP

.SH "Function Documentation"
.PP 
.SS "void pip_exit (intstatus)"

.PP
\fBName\fP
.RS 4
pip_exit
.RE
.PP
\fBSynopsis\fP
.RS 4
#include <\fBpip/pip\&.h\fP> 
.br
 void \fBpip_exit( int status )\fP;
.RE
.PP
\fBDescription\fP
.RS 4
When the main function or the start function of a PiP task returns with an integer value, then it has the same effect of calling \fBpip_exit\fP with the returned value\&.
.RE
.PP
\fBParameters:\fP
.RS 4
\fIstatus\fP This status is returned to PiP root\&.
.RE
.PP
\fBNote:\fP
.RS 4
This function can be used regardless to the PiP execution mode\&. \fCexit(3)\fP is called in the process mode and \fCpthread_exit(3)\fP is called in the pthread mode\&.
.RE
.PP
\fBSee Also:\fP
.RS 4
\fBpip_wait\fP 
.PP
\fBpip_trywait\fP 
.PP
\fBpip_wait_any\fP 
.PP
\fBpip_trywait_any\fP 
.RE
.PP

.SS "int pip_kill_all_tasks (void)"

.PP
\fBName\fP
.RS 4
pip_kill_all_tasks
.RE
.PP
\fBSynopsis\fP
.RS 4
#include <\fBpip/pip\&.h\fP> 
.br
int \fBpip_kill_all_tasks( void )\fP;
.RE
.PP
\fBNote:\fP
.RS 4
This function must be called from PiP root\&.
.RE
.PP
\fBReturns:\fP
.RS 4
Return 0 on success\&. Return an error code on error\&. 
.RE
.PP
\fBReturn values:\fP
.RS 4
\fIEPERM\fP The PiP library is not initialized yet 
.br
\fIEPERM\fP Not called from root 
.RE
.PP

.SS "void pip_abort (void)"

.PP
\fBName\fP
.RS 4
pip_abort 
.RE
.PP
\fBSynopsis\fP
.RS 4
#include <\fBpip/pip\&.h\fP> 
.br
void \fBpip_abort( void )\fP; 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Process-in-Process from the source code\&.
