.TH "PiP Synchronization Functions" 3 "Fri Dec 25 2020" "Process-in-Process" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PiP Synchronization Functions \- 
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBpip_yield\fP (int flag)"
.br
.RI "\fIYield\&. \fP"
.ti -1c
.RI "int \fBpip_barrier_init\fP (pip_barrier_t *barrp, int n)"
.br
.RI "\fIinitialize barrier synchronization structure \fP"
.ti -1c
.RI "int \fBpip_barrier_wait\fP (pip_barrier_t *barrp)"
.br
.RI "\fIwait on barrier synchronization in a busy-wait way \fP"
.ti -1c
.RI "int \fBpip_barrier_fin\fP (pip_barrier_t *barrp)"
.br
.RI "\fIfinalize barrier synchronization structure \fP"
.in -1c
.SH "Detailed Description"
.PP 
PiP synchronization functions

.PP
\fBDescription\fP
.RS 4
Synchronization functions for PiP tasks 
.RE
.PP

.SH "Function Documentation"
.PP 
.SS "int pip_yield (intflag)"

.PP
\fBName\fP
.RS 4
pip_yield
.RE
.PP
\fBSynopsis\fP
.RS 4
#include <\fBpip/pip\&.h\fP> 
.br
int \fBpip_yield( int flag )\fP;
.RE
.PP
\fBParameters:\fP
.RS 4
\fIflag\fP to specify the behavior of yielding\&. Unused and reserved for BLT/ULP (in PiP-v3)
.RE
.PP
\fBReturns:\fP
.RS 4
Thuis function always succeeds and returns zero\&.
.RE
.PP
\fBSee Also:\fP
.RS 4
sched_yield(Linux 2) 
.PP
pthread_yield(Linux 3) 
.RE
.PP

.SS "int pip_barrier_init (pip_barrier_t *barrp, intn)"

.PP
\fBName\fP
.RS 4
pip_barrier_init
.RE
.PP
\fBSynopsis\fP
.RS 4
#include <\fBpip/pip\&.h\fP> 
.br
int \fBpip_barrier_init( pip_barrier_t *barrp, int n )\fP;
.RE
.PP
\fBParameters:\fP
.RS 4
\fIbarrp\fP pointer to a PiP barrier structure 
.br
\fIn\fP number of participants of this barrier synchronization
.RE
.PP
\fBReturns:\fP
.RS 4
Return 0 on success\&. Return an error code on error\&.
.RE
.PP
\fBReturn values:\fP
.RS 4
\fIEPERM\fP PiP library is not yet initialized or already finalized 
.br
\fIEINAVL\fP \fCn\fP is invalid
.RE
.PP
\fBSee Also:\fP
.RS 4
\fBpip_barrier_wait\fP 
.PP
\fBpip_barrier_fin\fP 
.RE
.PP

.SS "int pip_barrier_wait (pip_barrier_t *barrp)"

.PP
\fBName\fP
.RS 4
pip_barrier_wait
.RE
.PP
\fBSynopsis\fP
.RS 4
#include <\fBpip/pip\&.h\fP> 
.br
int \fBpip_barrier_wait( pip_barrier_t *barrp )\fP;
.RE
.PP
\fBParameters:\fP
.RS 4
\fIbarrp\fP pointer to a PiP barrier structure
.RE
.PP
\fBReturns:\fP
.RS 4
Return 0 on success\&. Return an error code on error\&.
.RE
.PP
\fBReturn values:\fP
.RS 4
\fIEPERM\fP PiP library is not yet initialized or already finalized
.RE
.PP
\fBSee Also:\fP
.RS 4
\fBpip_barrier_init\fP 
.PP
\fBpip_barrier_fin\fP 
.RE
.PP

.SS "int pip_barrier_fin (pip_barrier_t *barrp)"

.PP
\fBName\fP
.RS 4
pip_barrier_fin
.RE
.PP
\fBSynopsis\fP
.RS 4
#include <\fBpip/pip\&.h\fP> 
.br
int \fBpip_barrier_fin( pip_barrier_t *barrp )\fP;
.RE
.PP
\fBParameters:\fP
.RS 4
\fIbarrp\fP pointer to a PiP barrier structure
.RE
.PP
\fBReturns:\fP
.RS 4
Return 0 on success\&. Return an error code on error\&. 
.RE
.PP
\fBReturn values:\fP
.RS 4
\fIEPERM\fP PiP library is not yet initialized or already finalized 
.br
\fIEBUSY\fP there are some tasks wating for barrier synchronization
.RE
.PP
\fBSee Also:\fP
.RS 4
\fBpip_barrier_init\fP 
.PP
\fBpip_barrier_wait\fP 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Process-in-Process from the source code\&.
