.TH "BLT/ULP Barrier Functions" 3 "Fri Jul 17 2020" "Process-in-Process" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BLT/ULP Barrier Functions \- 
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBpip_barrier_init\fP (pip_barrier_t *barrp, int n)"
.br
.RI "\fIinitialize barrier synchronization structure \fP"
.ti -1c
.RI "int \fBpip_barrier_wait\fP (pip_barrier_t *barrp)"
.br
.RI "\fIwait on barrier synchronization in a busy-wait way int \fBpip_barrier_wait( pip_barrier_t *barrp )\fP; \fP"
.ti -1c
.RI "int \fBpip_barrier_fin\fP (pip_barrier_t *barrp)"
.br
.RI "\fIfinalize barrier synchronization structure \fP"
.in -1c
.SH "Detailed Description"
.PP 
BLT/ULP barrier synchronization functions

.PP
\fBDescription\fP
.RS 4
BLT/ULP barrier synchronization functions
.RE
.PP
\fBDescription\fP
.RS 4
BLT/ULP mutex functions 
.RE
.PP

.SH "Function Documentation"
.PP 
.SS "int pip_barrier_init (pip_barrier_t *barrp, intn)"

.PP
\fBName\fP
.RS 4
pip_barrier_init
.RE
.PP
\fBSynopsis\fP
.RS 4
#include <\fBpip\&.h\fP> 
.br
int \fBpip_barrier_init( pip_barrier_t *barrp, int n )\fP;
.RE
.PP
\fBParameters:\fP
.RS 4
\fIbarrp\fP pointer to a PiP barrier structure 
.br
\fIn\fP number of participants of this barrier synchronization
.RE
.PP
\fBReturns:\fP
.RS 4
Return 0 on success\&. Return an error code on error\&. 
.RE
.PP
\fBReturn values:\fP
.RS 4
\fIEPERM\fP PiP library is not yet initialized or already finalized 
.br
\fIEINAVL\fP \fCn\fP is invalid
.RE
.PP
\fBNote:\fP
.RS 4
This barrier works on PiP tasks only\&.
.RE
.PP
\fBSee Also:\fP
.RS 4
pip_barrier_init(3), pip_barrier_fin(3), 
.RE
.PP

.SS "int pip_barrier_wait (pip_barrier_t *barrp)"

.PP
\fBName\fP
.RS 4
pip_barrier_wait
.RE
.PP
\fBSynopsis\fP
.RS 4
#include <\fBpip\&.h\fP> 
.br
int \fBpip_barrier_wait( pip_barrier_t *barrp )\fP;
.RE
.PP
\fBParameters:\fP
.RS 4
\fIbarrp\fP pointer to a PiP barrier structure
.RE
.PP
\fBReturns:\fP
.RS 4
Return 0 on success\&. Return an error code on error\&. 
.RE
.PP
\fBReturn values:\fP
.RS 4
\fIEPERM\fP PiP library is not yet initialized or already finalized
.RE
.PP
\fBSee Also:\fP
.RS 4
pip_barrier_init(3), pip_barrier_fin(3), 
.RE
.PP

.SS "int pip_barrier_fin (pip_barrier_t *barrp)"

.PP
\fBName\fP
.RS 4
pip_barrier_fin
.RE
.PP
\fBSynopsis\fP
.RS 4
#include <\fBpip\&.h\fP> 
.br
int \fBpip_barrier_fin( pip_barrier_t *barrp )\fP;
.RE
.PP
\fBParameters:\fP
.RS 4
\fIbarrp\fP pointer to a PiP barrier structure
.RE
.PP
\fBReturns:\fP
.RS 4
Return 0 on success\&. Return an error code on error\&. 
.RE
.PP
\fBReturn values:\fP
.RS 4
\fIEPERM\fP PiP library is not yet initialized or already finalized 
.br
\fIEBUSY\fP there are some tasks wating for barrier synchronization
.RE
.PP
\fBSee Also:\fP
.RS 4
pip_barrier_init(3), pip_barrier_wait(3), 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Process-in-Process from the source code\&.
