.TH "BLT/ULP Coupling/Decoupling Functions" 3 "Sun Jan 17 2021" "Process-in-Process" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BLT/ULP Coupling/Decoupling Functions \- 
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBpip_couple\fP (void)"
.br
.RI "\fICouple the curren task with the original kernel thread\&. \fP"
.ti -1c
.RI "int \fBpip_decouple\fP (pip_task_t *task)"
.br
.RI "\fIDecouple the curren task from the kernel thread\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
BLT/ULP coupling/decoupling functions

.PP
\fBDescription\fP
.RS 4
BLT/ULP coupling/decoupling functions 
.RE
.PP

.SH "Function Documentation"
.PP 
.SS "int pip_couple (void)"

.PP
\fBName\fP
.RS 4
pip_couple
.RE
.PP
\fBSynopsis\fP
.RS 4
#include <\fBpip/pip\&.h\fP> 
.br
int \fBpip_couple( void )\fP;
.RE
.PP
\fBReturns:\fP
.RS 4
Return 0 on success\&. Return an error code on error\&. 
.RE
.PP
\fBReturn values:\fP
.RS 4
\fIEPERM\fP PiP library is not yet initialized or already finalized 
.br
\fIEBUSY\fP the curren task is already coupled with a kernel thread 
.RE
.PP

.SS "int pip_decouple (pip_task_t *task)"

.PP
\fBName\fP
.RS 4
pip_decouple
.RE
.PP
\fBSynopsis\fP
.RS 4
#include <\fBpip/pip\&.h\fP> 
.br
int \fBpip_decouple( pip_task_t *sched )\fP
.RE
.PP
\fBParameters:\fP
.RS 4
\fItask\fP specify the scheduling task to schedule the decoupled task (calling this function)\&. If \fCNULL\fP, then the previously coupled pip_task takes place\&.
.RE
.PP
\fBReturns:\fP
.RS 4
Return 0 on success\&. Return an error code on error\&. 
.RE
.PP
\fBReturn values:\fP
.RS 4
\fIEPERM\fP PiP library is not yet initialized or already finalized 
.br
\fIEBUSY\fP the curren task is already decoupled from a kernel thread 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Process-in-Process from the source code\&.
