# $PIP_VERSION:$
# $PIP_license:$
# $RIKEN_copyright:$

top_builddir = ../..
top_srcdir = $(top_builddir)
srcdir = .

include $(top_srcdir)/build/var.mk
include $(srcdir)/../Test.common

SRCS	= dlmopen_count.c

PROGRAMS = dlmopen_count

PROGRAMS_TO_INSTALL = # nothing

include $(top_srcdir)/build/rule.mk
