.TH "pip_named_export" 3 "Wed Jul 1 2020" "PiP - Process-in-Process" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pip_named_export \- pip_named_export 
export an address of the calling PiP root or a PiP task to the others\&.
.PP
\fBSynopsis:\fP
.RS 4
#include <\fBpip\&.h\fP> int pip_named_export( void *exp, const char *format, \&.\&.\&. )
.RE
.PP
\fBDescription:\fP
.RS 4
Pass an address of a memory region to the other PiP task\&. Unlike the simmple \fCpip_export\fP and \fCpip_import\fP functions which can only export one address per task, \fCpip_named_export\fP and \fCpip_named_import\fP can associate a name with an address so that PiP root or PiP task can exchange arbitrary number of addressess\&.
.RE
.PP
\fBParameters:\fP
.RS 4
\fIexp\fP an address to be passed to the other PiP task 
.br
\fIformat\fP a \fCprintf\fP format to give the exported address a name\&. If this is \fCNULL\fP, then the name is assumed to be ''\&.
.RE
.PP
\fBReturns:\fP
.RS 4
Return 0 on success\&. Return an error code on error\&. 
.RE
.PP
\fBReturn values:\fP
.RS 4
\fIEPERM\fP \fCpip_init\fP is not yet called\&. 
.br
\fIEBUSY\fP The name is already registered\&. 
.br
\fIENOMEM\fP Not enough memory
.RE
.PP
\fBNote:\fP
.RS 4
The addresses exported by \fCpip_named_export\fP cannot be imported by calling \fCpip_import\fP, and vice versa\&.
.RE
.PP
\fBSee Also:\fP
.RS 4
pip_named_import(3) 
.RE
.PP

