.TH "pip_decouple" 3 "Wed Jul 1 2020" "PiP - Process-in-Process" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pip_decouple \- pip_decouple 
Decouple the curren task from the kernel thread
.PP
\fBParameters:\fP
.RS 4
\fItask\fP specify the scheduling task to schedule the decoupled task (calling this function)
.RE
.PP
\fBReturns:\fP
.RS 4
Return 0 on success\&. Return an error code on error\&. 
.RE
.PP
\fBReturn values:\fP
.RS 4
\fIEPERM\fP PiP library is not yet initialized or already finalized 
.br
\fIEBUSY\fP the curren task is already decoupled from a kernel thread 
.RE
.PP

