.TH "pip_fin" 3 "Wed Jul 1 2020" "PiP - Process-in-Process" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pip_fin \- pip_fin 
Finalize the PiP library
.PP
\fBSynopsis:\fP
.RS 4
#include <\fBpip\&.h\fP> 
.br
int pip_fin( void );
.RE
.PP
\fBDescription:\fP
.RS 4
This function finalizes the PiP library\&. After calling this, most of the PiP functions will return the error code \fCEPERM\fP\&.
.RE
.PP
\fBReturns:\fP
.RS 4
zero is returned if this function succeeds\&. On error, error number is returned\&. 
.RE
.PP
\fBReturn values:\fP
.RS 4
\fIEPERM\fP \fCpip_init\fP is not yet called 
.br
\fIEBUSY\fP \fCone\fP or more PiP tasks are not yet terminated
.RE
.PP
\fBNotes:\fP
.RS 4
The behavior of calling \fCpip_init\fP after calling this \fCpip_fin\fP is note defined and recommended to do so\&.
.RE
.PP

.br

.br
\fBSee Also:\fP
.RS 4
pip_init(3) 
.RE
.PP

