.TH "pip_get_mode_str" 3 "Wed Jul 1 2020" "PiP - Process-in-Process" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pip_get_mode_str \- pip_get_mode_str 
get a character string of the current execution mode
.PP
\fBSynopsis:\fP
.RS 4
#include <\fBpip\&.h\fP> char *pip_get_mode_str( void );
.RE
.PP
\fBReturns:\fP
.RS 4
Return the name string of the current execution mode\&. If PiP library is note initialized yet, then thiss return \fCNULL\fP\&. 
.RE
.PP

