.TH "pip_export" 3 "Wed Jul 1 2020" "PiP - Process-in-Process" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pip_export \- pip_export 
export an address
.PP
\fBSynopsis:\fP
.RS 4
#include <\fBpip\&.h\fP> int pip_export( void *exp );
.RE
.PP
\fBDescription:\fP
.RS 4
Pass an address of a memory region to the other PiP task\&. This is a very naive implementation in PiP v1 and deprecated\&. Once a task export an address, there is no way to change the exported address or undo export\&.
.RE
.PP
\fBParameters:\fP
.RS 4
\fIexp\fP An addresss
.RE
.PP
\fBReturns:\fP
.RS 4
Return 0 on success\&. Return an error code on error\&. 
.RE
.PP
\fBReturn values:\fP
.RS 4
\fIEPERM\fP PiP library is not initialized yet
.RE
.PP
\fBSee Also:\fP
.RS 4
pip_import(3), pip_named_export(3), pip_named_import(3), pip_named_tryimport(3) 
.RE
.PP

