.TH "pip_isa_root" 3 "Wed Jul 1 2020" "PiP - Process-in-Process" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pip_isa_root \- pip_isa_root 
check if calling PiP task is a PiP root or not
.PP
\fBSynopsis:\fP
.RS 4
#include <\fBpip\&.h\fP> int pip_isa_root( void );
.RE
.PP
\fBReturns:\fP
.RS 4
Return a non-zero value if the caller is the PiP root\&. Otherwise this returns zero\&. 
.RE
.PP

