.TH "pip_is_shared_fd" 3 "Wed Jul 1 2020" "PiP - Process-in-Process" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pip_is_shared_fd \- pip_is_shared_fd 
check if file descriptors are shared or not\&. This is equivalent with the \fCpip_is_threaded\fP function\&.
.PP
\fBSynopsis:\fP
.RS 4
#include <\fBpip\&.h\fP> int pip_is_shared_fd( int *flagp );
.RE
.PP
\fBParameters:\fP
.RS 4
\fIset\fP to a non-zero value if FDs are shared
.RE
.PP
\fBReturns:\fP
.RS 4
Return 0 on success\&. Return an error code on error\&. 
.RE
.PP
\fBReturn values:\fP
.RS 4
\fIEPERM\fP The PiP library is not initialized yet 
.RE
.PP

