.TH "pip_is_initialized" 3 "Wed Jul 1 2020" "PiP - Process-in-Process" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pip_is_initialized \- pip_is_initialized 
Query is PiP library is already initialized
.PP
\fBSynopsis:\fP
.RS 4
#include <\fBpip\&.h\fP> int pip_is_initialized( void );
.RE
.PP
\fBReturns:\fP
.RS 4
Return a non-zero value if PiP is already initialized\&. Otherwise this returns zero\&. 
.RE
.PP

