.TH "pip_named_tryimport" 3 "Wed Jul 1 2020" "PiP - Process-in-Process" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pip_named_tryimport \- pip_named_tryimport 
import the named exported address (non-blocking)
.PP
\fBSynopsis:\fP
.RS 4
#include <\fBpip\&.h\fP> int pip_named_tryimport( int pipid, void **expp, const char *format, \&.\&.\&. )
.RE
.PP
\fBDescription:\fP
.RS 4
Import an address exported by the specified PiP task and having the specified name\&. If it is not exported yet, this returns \fCEAGAIN\fP\&.
.RE
.PP
\fBParameters:\fP
.RS 4
\fIpipid\fP The PiP ID to import the exposed address 
.br
\fIexpp\fP The starting address of the exposed region of the PiP task specified by the \fIpipid\fP\&. 
.br
\fIformat\fP a \fCprintf\fP format to give the exported address a name
.RE
.PP
\fBNote:\fP
.RS 4
The addresses exported by \fCpip_export\fP cannot be imported by calling \fCpip_named_import\fP, and vice versa\&.
.RE
.PP
\fBReturns:\fP
.RS 4
Zero is returned if this function succeeds\&. On error, an error number is returned\&. 
.RE
.PP
\fBReturn values:\fP
.RS 4
\fIEPERM\fP \fCpip_init\fP is not yet called\&. 
.br
\fIEINVAL\fP The specified \fCpipid\fP is invalid 
.br
\fIENOMEM\fP Not enough memory 
.br
\fIECANCELED\fP The target task is terminated 
.br
\fIEAGAIN\fP Target is not exported yet
.RE
.PP
\fBSee Also:\fP
.RS 4
pip_named_export(3), pip_named_import(3), pip_export(3), pip_import(3) 
.RE
.PP

