# $PIP_VERSION:$
# $PIP_license:$
# $RIKEN_copyright:$

top_builddir = ..
top_srcdir = $(top_builddir)
srcdir = .

include $(top_srcdir)/build/var.mk

PROGRAMS_TO_INSTALL = piplnlibs
MAN1_SRCS = piplnlibs

include $(top_srcdir)/build/rule.mk
