#!/bin/sh

cc=$1
ofile=$2
tfile="${ofile}.tmp"

commit_hash=`git rev-parse HEAD`
build_os=`uname -s -r -v`

if [ "x$cc" == "x" ]; then
    cc=`/bin/which gcc 2> /dev/null`
else
    cc=`/bin/which ${cc} 2> /dev/null`
fi
if [ $? != 0 ]; then
    echo "Unable to find a C compiler" > /dev/stderr
    exit 1
fi
build_cc=`${cc} --version 2>&1 | head -n 1`
if [ x"${build_cc}" == x ]; then
    build_cc=${cc}
fi

cat > $tfile << EOF
/*** DO NOT EDIT THIS FILE ***/

#define COMMIT_HASH \"${commit_hash}\"
#define BUILD_OS \"${build_os}\"
#define BUILD_CC \"${build_cc}\"
EOF

if [ -f $ofile ]; then
    if diff $ofile $tfile > /dev/null 2>&1; then
	rm -f $tfile
    else
	mv -f $tfile $ofile
    fi
else
    mv -f $tfile $ofile
fi
