#!/bin/sh

# $PIP_license: <Simplified BSD License>
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
# 
#     Redistributions of source code must retain the above copyright notice,
#     this list of conditions and the following disclaimer.
# 
#     Redistributions in binary form must reproduce the above copyright notice,
#     this list of conditions and the following disclaimer in the documentation
#     and/or other materials provided with the distribution.
# 
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
# LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
# CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
# SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
# INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
# CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
# ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF
# THE POSSIBILITY OF SUCH DAMAGE.
# $
# $RIKEN_copyright: Riken Center for Computational Sceience (R-CCS),
# System Software Development Team, 2016-2020
# $
# $PIP_VERSION: Version 2.0.0$
#
# $Author: Atsushi Hori (R-CCS) mailto: ahori@riken.jp or ahori@me.com
# $

cc=$1
ofile=$2
tfile="${ofile}.tmp"

commit_hash=`git rev-parse HEAD`
build_os=`uname -s -r -v`

if [ "x$cc" == "x" ]; then
    cc=`/bin/which gcc 2> /dev/null`
else
    cc=`/bin/which ${cc} 2> /dev/null`
fi
if [ $? != 0 ]; then
    echo "Unable to find a C compiler" > /dev/stderr
    exit 1
fi
build_cc=`${cc} --version 2>&1 | head -n 1`
if [ x"${build_cc}" == x ]; then
    build_cc=${cc}
fi

echo >  $tfile
echo >> $tfile  "/*** DO NOT EDIT THIS FILE ***/"
echo >> $tfile
echo >> $tfile "#define COMMIT_HASH \"${commit_hash}\""
echo >> $tfile "#define BUILD_OS \"${build_os}\""
echo >> $tfile "#define BUILD_CC \"${build_cc}\""

if [ -f $ofile ]; then
    if diff $ofile $tfile > /dev/null 2>&1; then
	rm -f $tfile
    else
	mv -f $tfile $ofile
    fi
else
    mv -f $tfile $ofile
fi
