.TH "pip-man" 1 "Wed Jul 1 2020" "PiP - Process-in-Process" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pip-man \- 
.PP
show PiP man page  

.SH "SYNOPSIS"
.PP
\fC\fBpip-man\fP \fP[ \fBMAN_OPTS\fP ] [ \fBPIP_TOPIC\fP ] 
.SH "Author"
.PP 
Generated automatically by Doxygen for PiP - Process-in-Process from the source code\&.
