.TH "pip-exec" 1 "Wed Jul 1 2020" "PiP - Process-in-Process" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pip-exec \- 
run programs as PiP tasks  

.SH "SYNOPSIS"
.PP
\fC\fBpip-exec\fP \fP[OPTIONS] <program> \&.\&.\&. [ : \&.\&.\&. ]
.SH "DESCRIPTION"
.PP
\fBRun\fP a program as PiP task(s)\&. Mutiple programs can be specified by separating them with ':'\&.
.PP
-n \fB<N>\fP number of tasks
.br
-f \fB<FUNC>\fP function name to start
.br
-c \fB<CORE>\fP specify the CPU core number to bind core(s)
.br
-r core binding in the round-robin fashion
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for PiP - Process-in-Process from the source code\&.
