.TH "pip-check" 1 "Wed Jan 15 2020" "PiP - Process-in-Process" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pip-check \- 
.PP
PiP binary checking program\&.  

.SH "SYNOPSIS"
.PP
\fC\fBpipcheck\fP \fBpip-prog\fP \fP[\&.\&.\&.] 
.SH "Author"
.PP 
Generated automatically by Doxygen for PiP - Process-in-Process from the source code\&.
