.TH "pip-mode" 1 "Wed Jul 1 2020" "PiP - Process-in-Process" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pip-mode \- 
.PP
Set PiP execution mode\&.  

.SH "SYNOPSIS"
.PP
\fC\fBpip-mode\fP \fP[\fBpipenv-option\fP] [\fBcommands\fP \&.\&.\&.]
.SH "OPTIONS"
.PP
The following options are avilable\&. If no of them specified, then the compiled output file can be used as both PiP root and PiP task\&.
.SS "-P"
If specified, PiP will run with the 'process' mode
.SS "-p"
If specified, PiP will run with the 'process' mode (preload)
.SS "-c"
If specified, PiP will run with the 'process' mode (pip clone)
.SS "-t"
If specified, PiP will run with the 'thread' mode 
.SH "Author"
.PP 
Generated automatically by Doxygen for PiP - Process-in-Process from the source code\&.
