.TH "pipcc" 1 "Fri Oct 2 2020" "PiP - Process-in-Process" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pipcc \- 
.PP
C compiler driver for PiP\&.  

.SH "SYNOPSIS"
.PP
\fC\fBpipcc\fP \fP[\fBcc-command-options\fP] 
.SH "Author"
.PP 
Generated automatically by Doxygen for PiP - Process-in-Process from the source code\&.
