.TH "piplnlibs" 1 "Wed Dec 26 2018" "PiP - Process-in-Process" \" -*- nroff -*-
.ad l
.nh
.SH NAME
piplnlibs \- 
.PP
command to create symbolic links to the SOLIBs in the patched GLIBC\&.  

.SH "SYNOPSIS"
.PP
\fC\fBpiplnlibs\fP \fP[\fB-Rrs\fP] [\fB-a\fP DIR]
.SH "DESCRIPTION"
.PP
This command creates a number of symbolic links to the SOLIBs which are not installed by the patched GLIBC installation\&.
.SH "OPTIONS"
.PP
.SS "-a"
Add DIR to directories to search SOLIBS to create symbolic links\&.
.SS "-R"
Remove symbolic links to SOLIBs in libdir of patched GLIBC, and do not create symbolic links\&.
.SS "-r"
Remove symbolic links to SOLIBs in libdir of patched GLIBC before creating\&.
.SS "-s"
Silent mode\&.
.SH "ENVIRONMENT"
.PP
.SS "PIP_LIBRARY_PATH"
Symbolic links to SOLIBs in the directories specified by PIP_LIBRARY_PATH will be also created\&.
.SS "LD_LIBRARY_PATH"
If PIP_LIBRARY_PATH is not set, LD_LIBRARY_PATH is used instead\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for PiP - Process-in-Process from the source code\&.
