.TH "piprun" 1 "Fri Oct 30 2020" "PiP - Process-in-Process" \" -*- nroff -*-
.ad l
.nh
.SH NAME
piprun \- 
.PP
command to run programs using PiP  

.SH "SYNOPSIS"
.PP
\fC\fBpiprun\fP \fP[-n <N>] <program> \&.\&.\&.
.SH "DESCRIPTION"
.PP
\fBRun\fP a program as a PiP task\&. If \fB-n\fP <N> is specified, then \fBN\fP PiP tasks are created and run\&.
.SH "ENVIRONMENT"
.PP
.SS "PIP_MODE"

.SH "Author"
.PP 
Generated automatically by Doxygen for PiP - Process-in-Process from the source code\&.
