.TH "pips" 1 "Wed Jul 1 2020" "PiP - Process-in-Process" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pips \- 
.PP
List or kill running PiP tasks\&.  

.SH "SYNOPSIS"
.PP
\fC\fBpips\fP \fP[\fBoptions\fP] [\fBpip-command\fP \&.\&.\&.]
.SH "OPTIONS"
.PP
The following options are avilable\&. If none of them specified, then this sends TERM signal to all running PiP tasks including PiP root\&.
.SS "-s \\b SIGNAL"
Send the specified signal to the specified PiP tasks
.SS "-k"
same as \fB-s\fP \fBTERM\fP 
.SS "-l"
List (ps command) running PiP tasks specified\&. This is the default action\&.
.SS "--list"
same as \fB-l\fP 
.SS "-t"
Show running PiP tasks specified by using the top command\&. Due to the top command limitation, only 20 PiP tasks will be shown\&.
.SS "--top"
same as \fB-t\fP 
.SH "Author"
.PP 
Generated automatically by Doxygen for PiP - Process-in-Process from the source code\&.
