.TH "printpipmode" 1 "Wed Jan 15 2020" "PiP - Process-in-Process" \" -*- nroff -*-
.ad l
.nh
.SH NAME
printpipmode \- 
.PP
command to print current PiP mode  

.SH "SYNOPSIS"
.PP
\fBprintpipmode\fP 
.SH "DESCRIPTION"
.PP
\fBThis\fP command prints the current PiP mode setting 
.SH "Author"
.PP 
Generated automatically by Doxygen for PiP - Process-in-Process from the source code\&.
