.TH "pip-exec" 1 "Mon Jul 6 2020" "Process-in-Process" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pip-exec \- pip-exec 
run program(s) as PiP tasks
.PP
\fBSynopsis\fP
.RS 4
pip-exec [OPTIONS] <program> \&.\&.\&. [ : \&.\&.\&. ]
.RE
.PP
\fBDescription\fP
.RS 4
\fBRun\fP a program as PiP task(s)\&. Mutiple programs can be specified by separating them with ':' to share the same virtual address space with the \fCpip-exec\fP command\&.
.RE
.PP
\fBParameters:\fP
.RS 4
\fI-n N\fP number of tasks 
.br
\fI-f FUNC\fP function name to start 
.br
\fI-c CORE\fP specify the CPU core number to bind core(s) 
.br
\fI-r\fP core binding in the round-robin fashion
.RE
.PP
\fBSee Also:\fP
.RS 4
pipcc(1) 
.RE
.PP

