.TH "pip-check" 1 "Thu Oct 22 2020" "Process-in-Process" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pip-check \- 
.PP
PiP binary checking program\&.  

.PP
\fBSynopsis\fP
.RS 4
pip-check [OPTIONS] \fBPIP-PROG\fP [\&.\&.\&.]
.RE
.PP
\fBParameters:\fP
.RS 4
\fI-r\fP check if a\&.out can be PiP root 
.br
\fI-t\fP check if a\&.out can be PiP task 
.br
\fI-b\fP check if a\&.out can be PiP root and/or PiP task (default) 
.br
\fI-v\fP show reson
.RE
.PP
\fBSee Also:\fP
.RS 4
pipcc(1) 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Process-in-Process from the source code\&.
