.TH "pip-mode" 1 "Fri Oct 30 2020" "Process-in-Process" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pip-mode \- pip-mode 
Set PiP execution mode
.PP
\fBSynopsis\fP
.RS 4
pip-mode [OPTION] [PIP-COMMAND]
.RE
.PP
\fBDescription\fP
.RS 4
The following options are avilable\&. If no of them specified, then the compiled output file can be used as both PiP root and PiP task\&.
.RE
.PP
\fBParameters:\fP
.RS 4
\fI-P\fP 'process' mode 
.br
\fI-L\fP 'process:preload' mode 
.br
\fI-C\fP 'process:clone' mode 
.br
\fI-G\fP 'process:got' mode 
.br
\fI-T\fP 'thread' mode 
.br
\fI-u\fP Show usage
.RE
.PP
\fBSee Also:\fP
.RS 4
pip-exec 
.PP
printpipmode 
.RE
.PP

