.TH "pipfc" 1 "Thu Dec 17 2020" "Process-in-Process" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pipfc \- pipfc 
Fortran compiler driver for PiP
.PP
\fBSynopsis\fP
.RS 4
pipfc [PIP-OPTIONS] [FC-COMMAND-OPTIONS_AND_ARGS]
.RE
.PP
\fBParameters:\fP
.RS 4
\fI-piproot\fP the compile (and link) as a PiP root 
.br
\fI-piptask\fP the compile (and link) as a PiP task 
.br
\fI-nopip\fP No PiP related settings will be applied
.RE
.PP
\fBNote:\fP
.RS 4
The \fB-piproot\fP and \fB-piptask\fP options can be specified at the same time\&. In this case, the compiled object can be both of PiP root and PiP task\&. This is also the default behavior when none of them is not specified\&.
.RE
.PP
\fBEnvironment\fP
.RS 4
\fC$\fP(FC) is used to specify a Fortran compiler
.RE
.PP
\fBSee Also:\fP
.RS 4
pip-exec(1), pip-mode(1) 
.RE
.PP

