.TH "piplnlibs" 1 "Fri Jul 17 2020" "Process-in-Process" \" -*- nroff -*-
.ad l
.nh
.SH NAME
piplnlibs \- piplnlibs 
command to create symbolic links to the SOLIBs in the install directory of the patched GLIBC\&.
.PP
\fBSynopsis\fP
.RS 4
piplnlibs [ OPTIONS ]
.RE
.PP
\fBDescription\fP
.RS 4
This command creates a number of symbolic links to the SOLIBs which are not installed by the patched GLIBC installation\&.
.RE
.PP
\fBParameters:\fP
.RS 4
\fI-r\fP Remove symbolic links to SOLIBs in /home/ahori/PiP/x86_64/install/lib before creating\&. 
.br
\fI-s\fP Silent mode\&. 
.RE
.PP

