.TH "pips" 1 "Sat Sep 26 2020" "Process-in-Process" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pips \- 
.PP
List or kill running PiP tasks\&.  

.PP
\fBSynopsis\fP
.RS 4
pips [OPTIONS] [PIP-COMMAND \&.\&.\&.]
.RE
.PP
\fBParameters:\fP
.RS 4
\fI-s\fP Send the specified signal (followed by the '-b' option) to the specified PiP tasks 
.br
\fI-k\fP same as \fB-s\fP 
.br
\fI-l\fP List (using the Linux ps command) running PiP tasks specified\&. This is the default action\&. 
.br
\fI-t\fP Show running PiP tasks specified by using the top command\&. Due to the top command limitation, only 20 PiP tasks will be shown\&.
.RE
.PP
\fBSee Also:\fP
.RS 4
pip-exec 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Process-in-Process from the source code\&.
