.TH "pips" 1 "Tue Sep 29 2020" "Process-in-Process" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pips \- pips 
List or kill running PiP tasks
.PP
\fBSynopsis\fP
.RS 4
pips [ OPTION ] [ PIP-PROG-NAME \&.\&.\&.]
.RE
.PP
\fBDescription\fP
.RS 4
The following options are avilable\&.
.RE
.PP
\fBParameters:\fP
.RS 4
\fI-s SIGNAL\fP Send the specified signal to the specified PiP tasks 
.br
\fI-k\fP Same as 'pips -s TERM' 
.br
\fI-l\fP List (ps command) running PiP tasks specified\&. This is the default action\&. 
.br
\fI--list\fP Same as 'pips -l' 
.br
\fI-t\fP Show running PiP tasks specified by using the top command\&. 
.br
\fI-v\fP Verbose mode 
.br
\fI--top\fP Same sa 'pip -t'
.RE
.PP
\fBSee Also:\fP
.RS 4
ps(1), top(1) 
.RE
.PP

