.TH "pips" 1 "Mon Feb 1 2021" "Process-in-Process" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pips \- pips 
List or kill running PiP tasks
.PP
\fBSynopsis\fP
.RS 4
pips [a][u][x] [PIPS-OPTIONS] [-] [PATTERN \&.\&.]
.RE
.PP
\fBParameters:\fP
.RS 4
\fIa|u|x\fP similar to the aux options of the Linux ps command 
.br
\fI--root\fP List PiP root(s) 
.br
\fI--task\fP List PiP task(s) 
.br
\fI--family\fP List PiP root(s) and PiP task(s) in family order 
.br
\fI--kill\fP Send SIGTERM to PiP root(s) and task(s) 
.br
\fI--signal\fP Send a signal to PiP root(s) and task(s)\&. This option must be followed by a signal number of name\&. 
.br
\fI--ps\fP Run the ps Linux command\&. This option may have \fCps\fP command option(s) separated by comma (,) 
.br
\fI--top\fP Run the top Linux command\&. This option may have \fCtop\fP command option(s) separated by comma (,) 
.br
\fI-\fP Simply ignored\&. This option can be used to avoid the ambiguity of the options\&.
.RE
.PP
\fBDescription\fP
.RS 4
\fCpips\fP is a filter to target only PiP tasks (including PiP root) to show status like the way what the \fCps\fP commands does and send signals to the selected PiP tasks\&.
.RE
.PP
Just like the \fCps\fP command, \fCpips\fP can take the most familiar \fCps\fP options \fCa\fP, \fCu\fP, \fCx\fP\&. Here is an example;
.PP
.PP
.nf
$ pips
PID   TID   TT       TIME     PIP COMMAND
18741 18741 pts/0    00:00:00 RT  pip-exec
18742 18742 pts/0    00:00:00 RG  pip-exec
18743 18743 pts/0    00:00:00 RL  pip-exec
18741 18744 pts/0    00:00:00 0T  a
18745 18745 pts/0    00:00:00 0G  b
18746 18746 pts/0    00:00:00 0L  c
18747 18747 pts/0    00:00:00 1L  c
18741 18748 pts/0    00:00:00 1T  a
18749 18749 pts/0    00:00:00 1G  b
18741 18750 pts/0    00:00:00 2T  a
18751 18751 pts/0    00:00:00 2G  b
18741 18752 pts/0    00:00:00 3T  a
.fi
.PP
.PP
here, there are 3 \fCpip-exec\fP root processes running\&. Four pip tasks running program 'a' with the ptherad mode, three PiP tasks running program 'b' with the process:got mode, and two PiP tasks running program 'c' with the process:preload mode\&.
.PP
Unlike the \fCps\fP command, two columns 'TID' and 'PIP' are added\&. The 'TID' field is to identify PiP tasks in pthread execution mode\&. three PiP tasks running in the pthread mode\&. As for the 'PiP' field, if the first letter is 'R' then that pip task is running as a PiP root\&. If this letter is a number from '0' to '9' then this is a PiP task (not root)\&. The number is the least-significant digit of the PiP ID of that PiP task\&. The second letter represents the PiP execution mode which is common with PiP root and task\&. 'L' is 'process:preload,' 'C' is 'process:pipclone,', 'G' is 'process:got,' and 'T' is 'thread\&.'
.PP
The last 'COMMAND' column of the \fCpips\fP output may be different from what the \fCps\fP command shows, although it looks the same\&. It represents the command, not the command line consisting of a command and its argument(s)\&. More precisely speaking, it is the first 14 letters of the command\&. This comes from the PiP's specificity\&. PiP tasks are not created by using the normal \fCexec\fP systemcall and the Linux assumes the same command line with the pip root process which creates the pip tasks\&.
.PP
If users want to have the other \fCps\fP command options other than 'aux', then refer to the \fC--ps\fP option described below\&. But in this case, the command lines of PiP tasks (excepting PiP roots) are not correct\&.
.PP
.PD 0
.IP "\(bu" 2
\fC--root\fP (\fC-r\fP) Only the PiP root tasks will be shown\&. 
.PP
.nf
$ pips --root
PID   TID   TT       TIME     PIP COMMAND
18741 18741 pts/0    00:00:00 RT  pip-exec
18742 18742 pts/0    00:00:00 RG  pip-exec
18743 18743 pts/0    00:00:00 RL  pip-exec

.fi
.PP

.PP
.PD 0
.IP "\(bu" 2
\fC--task\fP (\fC-t\fP) Only the PiP tasks (excluding root) will be shown\&. If both of \fC--root\fP and \fC--task\fP are specified, then firstly PiP roots are shown and then PiP tasks will be shown\&. 
.PP
.nf
$ pips --tasks
PID   TID   TT       TIME     PIP COMMAND
18741 18744 pts/0    00:00:00 0T  a
18745 18745 pts/0    00:00:00 0G  b
18746 18746 pts/0    00:00:00 0L  c
18747 18747 pts/0    00:00:00 1L  c
18741 18748 pts/0    00:00:00 1T  a
18749 18749 pts/0    00:00:00 1G  b
18741 18750 pts/0    00:00:00 2T  a
18751 18751 pts/0    00:00:00 2G  b
18741 18752 pts/0    00:00:00 3T  a

.fi
.PP

.PP
.PD 0
.IP "\(bu" 2
\fC--family\fP (\fC-f\fP) All PiP roots and tasks of the selected PiP tasks by the \fCPATTERN\fP optional argument of \fCpips\fP\&. 
.PP
.nf
$ pips - a
PID   TID   TT       TIME     PIP COMMAND
18741 18744 pts/0    00:00:00 0T  a
18741 18748 pts/0    00:00:00 1T  a
18741 18750 pts/0    00:00:00 2T  a
$ pips --family a
PID   TID   TT       TIME     PIP COMMAND
18741 18741 pts/0    00:00:00 RT  pip-exec
18741 18744 pts/0    00:00:00 0T  a
18741 18748 pts/0    00:00:00 1T  a
18741 18750 pts/0    00:00:00 2T  a

.fi
.PP
 In this example, 'pips - a' (the - is needed not to confused the command name \fCa\fP as the \fCpips\fP option) shows the PiP tasks which is derived from the program \fCa\fP\&. The second run, 'pips --family a,' shows the PiP tasks of \fCa\fP and their PiP root (\fCpip-exec\fP, in this example)\&.
.PP
.PD 0
.IP "\(bu" 2
\fC--kill\fP (\fC-k\fP) Send SIGTERM signal to the selected PiP tasks\&. 
.IP "\(bu" 2
\fC--signal\fP (\fC-s\fP) \fCSIGNAL\fP Send the specified signal to the selected PiP tasks\&. 
.IP "\(bu" 2
\fC--ps\fP (\fC-P\fP) This option may be followed by the \fCps\fP command options\&. When this option is specified, the PIDs of selected PiP tasks are passed to the \fCps\fP command with the specified \fCps\fP command options, if given\&. 
.IP "\(bu" 2
\fC--top\fP (\fC-T\fP) This option may be followed by the \fCtop\fP command options\&. When this option is specified, the PIDs of selected PiP tasks are passed to the \fCtop\fP command with the specified \fCtop\fP command options, if given\&. 
.IP "\(bu" 2
\fCPATTERN\fP The last argument is the pattern(s) to select which PiP tasks to be selected and shown\&. This pattern can be a command name (only the first 14 characters are effective), PID, TID, or a Unix (Linux) filename matching pattern (if the fnmatch Python module is available)\&. 
.PP
.nf
$ pips - *-*
PID   TID   TT       TIME     PIP COMMAND
18741 18741 pts/0    00:00:00 RT  pip-exec
18742 18742 pts/0    00:00:00 RG  pip-exec
18743 18743 pts/0    00:00:00 RL  pip-exec

.fi
.PP

.PP
\fBNote:\fP
.RS 4
\fCpips\fP collects PiP tasks' status by using the Linux's \fCps\fP command\&. When the \fC--ps\fP or \fC--top\fP option is specified, the \fCps\fP or \fCtop\fP command is invoked after invoking the \fCps\fP command for information gathering\&. This, however, may result some PiP tasks may not appear in the invoked \fCps\fP or \fCtop\fP command when one or more PiP tasks finished after the first \fCps\fP command invocation\&. The same situation may also happen with the \fC--kill\fP or --signal option\&. 
.RE
.PP

